# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "dist/"

  # Default build command.
  command = "npm run build"

  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "api"

[context.deploy-preview.environment]
  PASSPHRASE = "demo"
  TWILIO_ACCOUNT_ID = "not so secret"
  TWILIO_AUTH_TOKEN = "also not so secret"
  TWILIO_PHONE_NUMBER = "1" # Ok grandma
