# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "dist/"

  # Default build command.
  command = "npm run build"

  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "api"

[context.deploy-preview.environment]
  PASSPHRASE = "demo"
  TWILIO_ACCOUNT_ID = "not so secret"
  TWILIO_AUTH_TOKEN = "also not so secret"
  TWILIO_PHONE_NUMBER = "1" # Ok grandma

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "form-action https:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; img-src 'self' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; object-src 'none';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'none'; payment 'none'"
